name: clean_marvel
description: A Flutter project to learn clean architecture.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  mockito: ^5.4.2

flutter:
  uses-material-design: true
